select * from 
medication_id,
patient_id, 
encounter_id, 
drug_id, 
name, 
quantity, 
frequency, 
dos, 
concat('<<deployment_id>>', '-',cast(patientid as varchar))   as vho_patient_id,
concat('<<deployment_id>>'','-',cast(encounterid as varchar)) as vho_encounter_id,
concat ('<<deployment_id>>', '-',cast(medication_id as varchar) ) as vho_medication_id, 
concat ('<<deployment_id>>', '-',cast(drug_id as varchar) ) as  vho_drug_id, 
signature, 
ndc_id, 
begin_date, 
end_date, 
' ' as dos_src,
dos_mod, 
begin_date_src, 
begin_date_mod, 
end_date_src, 
end_date_mod, 
note, 
code, 
code_type, 
dosage, 
status, 
concat('<<deployment_id>>'','-',cast(provider_id as varchar)) as vho_provider_id,
drug_route, 
drug_form, 
provider_id, 
source_field, 
source_table, 
' ' as vh_projection_set_id,
original_medication_id, 
' ' as vh_location_id,
' ' as vh_ehr_id,
' ' as vh_practice_id,
' ' as vh_etl_id,
' ' as vh_pull_id,
active, 
dosage_unit, 
prescriber_npi, 
dispensing_supply_duration, 
category, 
refill_quantity, 
series_number, 
supply, 
drug_name, 
drug_strength, 
dispensing_quantity, 
max_dose_quantity, 
prescribe_electronically, 
reason_text, 
reason_code,
performer_npi, 
text, 
drug_manufacturer, 
expiration_date, 
criteria, 
dispense_date_mod, 
anatomical_location, 
class, 
dispense_date, 
dispense_date_src, 
effective_date, 
prescribed_date, 
reaction, 
min_dose_per_period, 
reaction_severity, 
reason_code_type, 
reason_for_discontinuation_code_type, 
refills_remaining, 
reason_for_discontinuation_code, 
reason_for_discontinuation_text, 
donotreconcile, 
vh_registry_id, 
vh_deployment_id from 

(
subquery
)
